# This workflow will install the dependencies and then build and deploy the
# React Storybook website to the gh-pages branch.

name: Publish React Storybook

on:
  workflow_dispatch:
  release:
    types: [created]

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  publish-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
      - run: npm ci
      - name: Build and deploy storybook
      - run: npm run deploy
