# This workflow will install the dependencies and then build and deploy the
# React Storybook website to the gh-pages branch.

name: Publish React Storybook

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  publish-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: npm run deploy
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
